### ISSUE TITLE
Multiple interfaces/grep 'file not found' error...

### ISSUE THREAD

**Issue by chrismarino** [coincashew/EthPillar#13]
My node had both wired and wireless interfaces up and I got a grep error 'file not found' from this [line](https://github.com/coincashew/EthPillar/blob/b1bbde3f7898a5174b4351563a4d75dd332f6644/functions.sh#L19). 
$interface_current was:
enp0s25
wlp2s0

Not sure what downstream effect this has, but my node had all kinds of consensus sync'ing probs. Tried a bunch of things, then finally had to take wlp2s0 down. Still seemed to have probs. Uninstalled/reinstalled and it sync'd right away?

**Comment by chrismarino** [comment]
Actually, hasn't fully sync'd dashboard says 100%, but the logs say sync="backfill: 01d20h19m (0.85%). Regardless, seems healthier today than with the interface errors.

**Comment by coincashew** [comment]
So it appears if you have two interfaces in $interface_currents, then it messes up.

Easy fix is to just take the first one with head -1
I'll make the change.
By disabling wlp2s0, it makes sense that the issue goes away.

Downstream effect is $network_current is not accurate and things like setting the ufw firewall will error.
Won't affect syncing. 
Backfill progress looks legit. :)

**Comment by coincashew** [comment]
Fixed in https://github.com/coincashew/EthPillar/commit/bc110c37ecb506ccceb3d17051ed1a65fa2f81f0

Thank you.
