### ISSUE TITLE
Peer count is zero...

### ISSUE THREAD

**Issue by chrismarino** [coincashew/EthPillar#15]
This [PR](https://github.com/coincashew/EthPillar/pull/14) should fix

**Comment by coincashew** [comment]
:+1: :+1:

**Comment by coincashew** [comment]
This change broke ubnntu's awk.
https://github.com/coincashew/EthPillar/issues/17

New fix implemented. Can you verify it still works on your zsh unbuntu?

**Comment by chrismarino** [comment]
Yes, this worked with Ubuntu 22.04, zsh 5.8.1

**Comment by coincashew** [comment]
Thanks for confirming!
