### ISSUE TITLE
Expose client's API endpoints option

### ISSUE THREAD

**Issue by chrismarino** [coincashew/EthPillar#16]
I'm using my node with external clients and had to add `--rest-address=0.0.0.0` to the nimbus config and `--JsonRpc.Host 0.0.0.0` to the nethermind config. Otherwise, the iptable rules only allow 127.0.0.1 access. 

It would be great to be able to set this option in the TUI, similar to how Rocket Pool shows it, [here](https://docs.rocketpool.net/guides/node/advanced-config#allowing-external-validator-clients-to-connect-to-the-smartnode)

**Comment by chrismarino** [comment]
Conversely, let the TUI set up the validator to point to external clients.

**Comment by coincashew** [comment]
Implemented in https://github.com/coincashew/EthPillar/commit/7b97308832ba5e9ef08da71c1982e48b84ad5528

The feature to allow a validator to point to external clients is useful for the power user. I'll add it to the backlog by opening a new issue.

**Comment by chrismarino** [comment]
I installed on a new system and got these errors when I tried to use this new feature: 

```
==> Exposing Nethermind RPC Access with flag: --JsonRpc.Host
/home/chris/git/ethpillar/functions.sh: line 755: /etc/systemd/system/execution.service.result: Permission denied
sed: can't read /etc/systemd/system/execution.service.result: No such file or directory
mv: cannot stat '/etc/systemd/system/execution.service.result': No such file or directory
```
This was tougher to identify since it completed and went back to the TUI.

```
==> Exposing Nimbus RPC Access with flag: --rest-address
/home/chris/git/ethpillar/functions.sh: line 755: /etc/systemd/system/consensus.service.result: Permission denied
sed: can't read /etc/systemd/system/consensus.service.result: No such file or directory
mv: cannot stat '/etc/systemd/system/consensus.service.result': No such file or directory
==> Configuration change complete.


```

**Comment by coincashew** [comment]
Looks like a user permission issue, as it can't create the .result file.
In the mean time, if you run ethpillar with sudo, I think it will work.
```
sudo ethpillar
```
