### ISSUE TITLE
Always Install submenuValidator

### ISSUE THREAD

**Issue by chrismarino** [coincashew/EthPillar#18]
When I first installed I did not want to configure a validators. Then when I wanted to generate keys I had to run
 `install-nimbus-nethermind.sh` directly. Did all the client install, updates, etc. Worried that I would have to re-sync my clients. Would have been better if the validator submenu was there with an option to install.

**Comment by coincashew** [comment]
Agreed. Will look into adding this scenario.

In the meantime, you can always refer to the manual installation and manually create the validator service files. They're consistent and compatible in setup. https://www.coincashew.com/coins/overview-eth/testnet-holesky-validator/step-5-installing-validator/installing-validator

**Comment by coincashew** [comment]
Resolved with https://github.com/coincashew/EthPillar/commit/746e00d538cb4a7d74352c5f6a18800bc66bb8a8

Now, users can add-on Validators functionality to existing Fallback staking nodes.
Alternatively, the preferred and cleaner way is to switch configurations or uninstall node.
via
```
ethpillar > system administration > uninstall node
```
or 
```
ethpillar > system administration > switch network
```

Thanks for this suggestion
