### ISSUE TITLE
Question: NixOS compatibility 

### ISSUE THREAD

**Issue by 0xJepsen** [coincashew/EthPillar#3]
I see in the documentation that ubuntu is recommended. However I would like to run my node with NixOS, has this compatibility been tested at all?

**Comment by coincashew** [comment]
Curious question.

Spunning up a VM with NixOS 23.11 minimal, I can see the differences between the OS's is too different.

Ubuntu 22.04LTS for sure works. Debian likely works.

I'd suggest test driving the workflow on holesky with Ubuntu.

**Comment by 0xJepsen** [comment]
I'll give it a try and let you know how it works. Making and and hardening my build next week.

**Comment by coincashew** [comment]
Any luck? Be sure to pull the latest updates.

**Comment by coincashew** [comment]
Closing, feel free to re-open if following up.
