### ISSUE TITLE
Provide a way to add more validator to existing EthPillar

### ISSUE THREAD

**Issue by htprww** [coincashew/EthPillar#36]
I already have several validators running in my machine using EthPillar. 
Now I want to add one more validator to the same machine. Is there an easy way to do that in EthPillar?

**Comment by coincashew** [comment]
Yes.

EthPillar > Validator Client > Generate / Import Validator Keys

From there you will pick 1 of 2 options. 
* Import validator keys from offline key generation or backup              │
* Add new or regenerate existing validator keys from Secret Recovery Phrase

**Comment by coincashew** [comment]
Added this to the FAQ
https://www.coincashew.com/coins/overview-eth/ethpillar#faq

POAP for your feedback is on the way. :)

**Comment by coincashew** [comment]
Re-open if there's still an issue.

Best of luck
