### ISSUE TITLE
Was not able to add to existing validator on pre-established EthPillar node with out of band csm validator...

### ISSUE THREAD

**Issue by chrismarino** [coincashew/EthPillar#40]
Can't say for sure this is an actual bug. I tried to use the new plugin branch to add a new CSM validator to an exsisting EthPillar deployment. I was able to generate keys successfully, but ran into probs when I tried to import them. Not exactly sure where the problem occured, but I was able to install them directly via the cli. That said, I did also have to change the permissions. 

Not sure where things when sideways, but I was also NOT asked for the key password when I imported them? 

Added csm validators to a EthPillar env where there is already a csm validator might not be the happy path, but the alternative for me will be to rebuld EthPillar on the machine. Not sure how disruptive that might be, so will have to try complete rebuild on my holesky node.

**Comment by coincashew** [comment]
Trying the 3.0.0 RC?

1) Install EthPillar from scratch
2) Select Solo Staking Node or other desired config
3) Finish the setup
4) Exit to back to terminal
5) Change branch
cd ~/git/ethpillar
git pull
git checkout plugins

6) Start 
ethpillar
 again. New plugin option should be there.

** Note if you've already installed a node, go straight to step 5.

**Comment by coincashew** [comment]
Hmm, hard to say, if you've customized some thing, unintended consequences may occur.

I've tested both workflows, from scratch and existing. More discussion on discord.

**Comment by coincashew** [comment]
out of band csm validator should be OK!

Using the new plugin architecture, ethpillar keeps everything separated and with minimal changes to the primary existing EL/CL and VC.

**Comment by chrismarino** [comment]
To be clear, I previously installed my csm validator as described [here](https://dvt-homestaker.stakesaurus.com/bonded-validators-setup/lido-csm/set-fee-recipient-address/method-2-configure-on-separate-validator-client).  Seemed like the new EthPillar paths, names, etc were the same, but didn't check carefully. 

My effort was not the case of an exiting  EthPillar node that was not running a CSM validator, so my entry point is different from adding a fresh new CSM validator systemd unit to an EthPillar install.

Regardless, I will try again to see if I can isolate what caused my probs.

**Comment by chrismarino** [comment]
Not a supported entry point. Not a bug.
