### ISSUE TITLE
Possibly not able to regenerate existing keys from mnemonic.. 

### ISSUE THREAD

**Issue by chrismarino** [coincashew/EthPillar#41]
Started with a clean install of Solo Validator config, then added CSM plugin. I have 2 CSM validators from the earlier install that I wanted to import into new node. There were no validator keys installed in either the Solo of CSM validators.

I used EthPillar TUI to `12 Add/Restore Validator Keys: From secret recovery phrase ` and tried three times to generate keys. Each time it failed with an error. 

I then went directly to the `deposit` cli and used the same command I used to generate them originally. 
`./deposit existing-mnemonic --num_validators 2 --chain holesky --eth1_withdrawal_address 0xF0179dEC45a37423EAD4FaD5fCb136197872EAd9`

And this was successful. I then imported these keys.

Then, I tried EthPillar again to be sure, but this time it worked? However, it then tried to import them but errored out because they were duplicates....

It is possible that didn't enter my mnemonic correctly. But three times? Then do it correctly on the CLI? Seems unlikely...

Perhaps there is a check that failed because the validator had not yet started? Or some other check. These validators are not yet active on Beaconchain since they were still in the queue and originally added just a day earlier. There were three empty directories for where the keys should have been saved. 

Otherwise, smooth install. Everything else seemed to work as before.

**Comment by coincashew** [comment]
Thanks for following up. 

Only thing that I can think of which changed and might cause the error is that the ethstaker-deposit-cli requires password length > 12. The OG deposit tool only required >= 8 length.
