### ISSUE TITLE
Option to override default editor (`nano`)

### ISSUE THREAD

**Issue by riordant** [coincashew/EthPillar#46]
I can see that the project enforces `nano` as the editor. would it be possible to add an option to override this, to instead select eg. `vim`?

**Comment by coincashew** [comment]
Hey,

Certainly that can be done.
An override to change the default text editor to vim could be configured in 
```
.env.overrides
```
Would that work for you?

**Comment by riordant** [comment]
Yes, that sounds awesome :)

**Comment by coincashew** [comment]
Done in https://github.com/coincashew/EthPillar/commit/56d2a5e3f6f38ec79a53a4ed1f26e6f368217bf6

To use this new option,

1. Update to v3.1.3 or higher
2. Create .env.overrides file from the example file
3. Uncomment the editor variable

```
cd $HOME/git/ethpillar
git pull
cp .env.overrides.example .env.overrides
#Uncomment the editor variable and update with your preferred editor e.g. vim
```
