### ISSUE TITLE
ethpillar script doesn't work with zsh...

### ISSUE THREAD

**Issue by chrismarino** [coincashew/EthPillar#7]
I run zsh and have to run `bash ethpillar` to get it to run. Tiny issue, but maybe a note in the docs would help. Not sure if/how the script could be modified, otherwise I would have sent a PR. Otherwise, works great!

**Comment by coincashew** [comment]
Thanks for your feedback!
Not familiar with zsh. Which OS are you running it under?
A note in the docs is a great idea. Easy fix for now.
Glad to hear it works great for you!

**Comment by chrismarino** [comment]
Ubuntu 22.04 
zsh 5.8.1

**Comment by coincashew** [comment]
Fixed in https://github.com/coincashew/EthPillar/commit/f91bd52897d22015a1067c1fe530dc94e2672c0b

Zsh no longer throws an error.

Please update to v1.5.0
