### ISSUE TITLE
Checkpoint sync....

### ISSUE THREAD

**Issue by chrismarino** [coincashew/EthPillar#8]
Noticed that Nimbus CC was taking a long time to sync, then I realized that there was no checkpoint sync configured. Setting it up is included in the CoinCashew [docs](https://www.coincashew.com/coins/overview-eth/guide-or-how-to-setup-a-validator-on-eth2-mainnet/part-iii-tips/how-to-re-sync-using-checkpoint-sync#nimbus).  Maybe best practice is to sync from scratch, but maybe the checkpoint sync could be included in the Tools section.

**Comment by coincashew** [comment]
With a default ethpillar one-liner install, nimbus's install should checkpoint sync automatically. Here's the code https://github.com/coincashew/EthPillar/blob/f91bd52897d22015a1067c1fe530dc94e2672c0b/deploy-nimbus-nethermind.py#L440C6-L440C9

You can force a checkpoint sync again in ethpillar > consensus client > resync consensus client.

Let me know if that works.

**Comment by coincashew** [comment]
I think what happened was nimbus checkpoint sync occurs, but it takes a while to backfill sync.

**Comment by chrismarino** [comment]
Hmmm.....Didn't work. Might be an artifact of zsh v. bash prob. Trying again w/v1.5.0.

```
╰─►  bash ethpillar                                                                                                                                                                     127 ↵
/home/chris/git/ethpillar/resync_consensus.sh: line 10: /functions.sh: No such file or directory
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by coincashew** [comment]
Simply
```
ethpillar
```
should work now with zsh.

Still doesn't work on the latest version?

**Comment by chrismarino** [comment]
Sorry for the confusion. I tried to resync before I updated, and got the same bash error (even when I executed `bash ethpillar'). The new version works without any errrors. But still not sync'ing quickly. Still seems too slow. Will look in to it later.

**Comment by coincashew** [comment]
Ok, thanks.

Checkpoint sync should enable your CL nimbus to sync to the head within seconds. However all CL clients will take about half a day to fully sync during what's known as the backfill step.

**Comment by chrismarino** [comment]
My re-install showed checkpoint sync working, etc. closing....

**Comment by chrismarino** [comment]
Closed
